### ISSUE TITLE
能加上多音字识别和返回首字母么？

### ISSUE THREAD

**Issue by laoqiuqiu** [snowie2000/PinYin4Delphi#1]
女红=nǚ gōng
解红=xiè hóng
解放=jiě fàng

**Comment by snowie2000** [comment]
不可能根据上下文识别多音字，那样的话你需要把整本新华词典放到里面去了。

`PyHeadOfHz` 就是返回首字母

**Comment by laoqiuqiu** [comment]
PyHeadOfHz 有bug

**Comment by snowie2000** [comment]
是什么bug呢

**Comment by laoqiuqiu** [comment]
![剪贴板图片 (12)](https://user-images.githubusercontent.com/16145623/80084070-f6bf4c80-8588-11ea-965d-333ebb7de0dd.jpg)

**Comment by snowie2000** [comment]
已解决。
